module.exports = {
	"yocto": { "symbol" : "y", "factor": -24 },
	"zepto": { "symbol" : "z", "factor": -21 },
	"atto": { "symbol" : "a", "factor": -18 },
	"femto": { "symbol" : "f", "factor": -15 },
	"pico": { "symbol" : "p", "factor": -12 },
	"nano": { "symbol" : "n", "factor": -9 },
	"micro": { "symbol" : "µ", "factor": -6 },
	"milli": { "symbol" : "m", "factor": -3 },
	"centi": { "symbol" : "c", "factor": -2 },
	"deci": { "symbol" : "d", "factor": -1 },

	"deca": { "symbol" : "da", "factor": 1 },
	"hecto": { "symbol" : "h", "factor": 2 },
	"kilo": { "symbol" : "k", "factor": 3 },
	"mega": { "symbol" : "M", "factor": 6 },
	"giga": { "symbol" : "G", "factor": 9 },
	"tera": { "symbol" : "T", "factor": 12 },
	"peta": { "symbol" : "P", "factor": 15 },
	"exa": { "symbol" : "E", "factor": 18 },
	"zetta": { "symbol" : "Z", "factor": 21 },
	"yotta": { "symbol" : "Y", "factor": 24 },
}
