module.exports = {
	"yoctometre": function(value) { return value * Math.pow(10, -24); },
	"zeptometre": function(value) { return value * Math.pow(10, -21); },
	"attometre":  function(value) { return value * Math.pow(10, -18); },
	"femtometre": function(value) { return value * Math.pow(10, -15); },
	"picometre": 	function(value) { return value * Math.pow(10, -12); },
	"nanometre": 	function(value) { return value * Math.pow(10, -9); },
	"micrometre": function(value) { return value * Math.pow(10, -6); },
	"millimetre": function(value) { return value * Math.pow(10, -3); },
	"centimetre": function(value) { return value * Math.pow(10, -2); },
	"decimetre": 	function(value) { return value * Math.pow(10, -1); },
	"metre": 			function(value) { return value * 1; },
	"hectometre": function(value) { return value * Math.pow(10, 2); },
	"kilometre": 	function(value) { return value * Math.pow(10, 3); },
	"megametre": 	function(value) { return value * Math.pow(10, 6); },
	"gigametre": 	function(value) { return value * Math.pow(10, 9); },
	"terametre": 	function(value) { return value * Math.pow(10, 12); },
	"petametre": 	function(value) { return value * Math.pow(10, 15); },
	"exametre": 	function(value) { return value * Math.pow(10, 18); },
	"zettametre": function(value) { return value * Math.pow(10, 21); },
	"yottametre": function(value) { return value * Math.pow(10, 24); },

}
